version: '2.2'
services:
  # website:
  #   build:
  #     context: .
  #     dockerfile: ./chessApp.Dockerfile
  #   ports:
  #     - 80:9000
  
  ssci:
    build:
      context: ./jenkins
      # dockerfile: ./jenkins/Dockerfile
    volumes:
    - /jenkins_home:/var/jenkins_home
    - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
